#define ZX_SYS_NULL 0
#define ZX_SYS_HANDLE_CLOSE 1
#define ZX_SYS_HANDLE_REPLACE 2
#define ZX_SYS_HANDLE_DUPLICATE 3
#define ZX_SYS_CHANNEL_CREATE 4
#define ZX_SYS_CHANNEL_READ 5
#define ZX_SYS_CHANNEL_WRITE 6
#define ZX_SYS_CHANNEL_CALL 7
