/* This is an autogenerated file, do not edit. */
void sys_handle_close(seL4_MessageInfo_t tag, uint64_t badge);
void sys_handle_duplicate(seL4_MessageInfo_t tag, uint64_t badge);
void sys_handle_replace(seL4_MessageInfo_t tag, uint64_t badge);
void sys_channel_create(seL4_MessageInfo_t tag, uint64_t badge);
void sys_channel_read(seL4_MessageInfo_t tag, uint64_t badge);
void sys_channel_write(seL4_MessageInfo_t tag, uint64_t badge);
void sys_channel_call(seL4_MessageInfo_t tag, uint64_t badge);
void sys_process_exit(seL4_MessageInfo_t tag, uint64_t badge);
void sys_process_create(seL4_MessageInfo_t tag, uint64_t badge);
void sys_process_start(seL4_MessageInfo_t tag, uint64_t badge);
void sys_process_read_memory(seL4_MessageInfo_t tag, uint64_t badge);
void sys_process_write_memory(seL4_MessageInfo_t tag, uint64_t badge);
void sys_fifo_create(seL4_MessageInfo_t tag, uint64_t badge);
void sys_fifo_read(seL4_MessageInfo_t tag, uint64_t badge);
void sys_fifo_write(seL4_MessageInfo_t tag, uint64_t badge);
void sys_debug_write(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_0(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_1(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_2(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_3(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_4(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_5(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_6(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_7(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_8(seL4_MessageInfo_t tag, uint64_t badge);
void sys_syscall_test_wrapper(seL4_MessageInfo_t tag, uint64_t badge);

#define NUM_SYSCALLS 145
