#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

apps-$(CONFIG_APP_ZIRCON_SERVER)        += zircon-server

# list of libraries the app needs to build
zircon-server-y                          = common libsel4 libmuslc libsel4vka libcpio libelf \
                                      libsel4allocman \
                                      libplatsupport libsel4platsupport libsel4muslcsys libsel4test \
                                      libsel4simple libsel4vspace libsel4utils libutils \
                                      libsel4debug

# set up correct simple lib for our kernel
zircon-server-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default

# add the tests app  as a component so that we can elf load it
zircon-server-components-y += zircon-test
zircon-server-components = $(addprefix $(STAGE_BASE)/bin/, $(zircon-server-components-y))

zircon-server: export COMPONENTS=${zircon-server-components}
zircon-server: ${zircon-server-components-y} kernel_elf $(zircon-server-y)
